# Generated by Django 4.1 on 2022-08-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=100)),
                ('abilname', models.CharField(max_length=100)),
                ('abilicon', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('armor', models.IntegerField()),
                ('attack_speed', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Attack Speed')),
                ('damage', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('initialmama', models.IntegerField(verbose_name='Initial Mana')),
                ('magic_resist', models.IntegerField(verbose_name='Magic Resist')),
                ('mana', models.IntegerField()),
                ('range', models.IntegerField()),
                ('traits', models.CharField(max_length=100)),
            ],
        ),
    ]
