# Generated by Django 4.1 on 2022-08-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('disc', models.CharField(max_length=100, verbose_name='Description')),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='champion',
            name='ability',
            field=models.CharField(max_length=1000),
        ),
    ]
