# Generated by Django 4.1 on 2022-08-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_traits_champion_trait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comp',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='comp',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
