# Generated by Django 4.1 on 2022-08-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_comp_options_comp_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comp',
            options={},
        ),
        migrations.RemoveField(
            model_name='comp',
            name='date',
        ),
    ]
