# Generated by Django 4.1 on 2022-08-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trait_alter_champion_options_alter_champion_ability'),
        ('main_app', '0003_alter_champion_ability'),
    ]

    operations = [
    ]
