# Generated by Django 4.1 on 2022-08-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_20220825_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='ability',
            field=models.CharField(max_length=500),
        ),
    ]
