# Generated by Django 4.1 on 2022-08-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_champion_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='disc',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
    ]
