# Generated by Django 4.1 on 2022-08-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_trait_disc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['name']},
        ),
    ]
