# Generated by Django 4.1 on 2022-08-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_augment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='augment',
            old_name='teir',
            new_name='tier',
        ),
        migrations.RenameField(
            model_name='trait',
            old_name='disc',
            new_name='desc',
        ),
    ]
