# Generated by Django 4.1 on 2022-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_teir_augment_tier_rename_disc_trait_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='initialmama',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='mana',
        ),
        migrations.AddField(
            model_name='champion',
            name='initialmana',
            field=models.CharField(default=1, max_length=100, verbose_name='Mana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='champion',
            name='damage',
            field=models.CharField(max_length=100, verbose_name='Damage'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hp',
            field=models.CharField(max_length=100, verbose_name='Health'),
        ),
    ]
