# Generated by Django 4.1 on 2022-08-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='champions',
            field=models.ManyToManyField(to='main_app.champion'),
        ),
    ]
