# Generated by Django 4.1 on 2022-08-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_trait_champions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trait',
            options={},
        ),
        migrations.RemoveField(
            model_name='trait',
            name='champions',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='traits',
        ),
        migrations.AddField(
            model_name='champion',
            name='traits',
            field=models.ManyToManyField(to='main_app.trait'),
        ),
    ]
