# Generated by Django 4.1 on 2022-08-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_trait_options_remove_trait_champions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='champions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
