# Generated by Django 4.1 on 2022-08-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_trait_options_remove_trait_champions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='trait',
            name='champions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='champion',
            name='traits',
        ),
        migrations.CreateModel(
            name='TraitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('charImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charimg', to='main_app.trait')),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='traits',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
