# Generated by Django 4.1 on 2022-08-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_trait_champions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='traits',
        ),
        migrations.AddField(
            model_name='champion',
            name='traits',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
