# Generated by Django 4.1 on 2022-08-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_trait_options_trait_champions_and_more'),
        ('main_app', '0017_remove_champion_traits_champion_traits'),
    ]

    operations = [
    ]
