# Generated by Django 4.1 on 2022-08-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20220829_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraitImage',
        ),
    ]
