# Generated by Django 4.1 on 2022-08-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_traitimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traitimg',
            options={'ordering': ['charname']},
        ),
        migrations.RenameField(
            model_name='traitimg',
            old_name='name',
            new_name='charname',
        ),
    ]
