# Generated by Django 4.1 on 2022-08-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_traitimg_options_rename_name_traitimg_charname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TraitImg',
            new_name='TraitImage',
        ),
    ]
