# Generated by Django 4.1 on 2022-08-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_rename_traitimg_traitimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraitImage',
        ),
    ]
