# Generated by Django 4.1 on 2022-08-29 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_delete_traitimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('charimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charimg', to='main_app.trait')),
            ],
            options={
                'ordering': ['charname'],
            },
        ),
    ]
